/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package artechemployeemanagementsystem;

import java.awt.Component;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Mofaqkhayrul Islam
 */
public class ProjectAllocation extends javax.swing.JPanel {

    /**
     * Creates new form ProjectAllocation
     */
    public ProjectAllocation() {
        initComponents();
         try
        {
            ConnectionDetails poo = new ConnectionDetails();
            Statement stmt = poo.con.createStatement();
         ResultSet rs = stmt.executeQuery("SELECT `project_id`, `name` FROM `project_details` ;");
         ArrayList<String> groupNames = new ArrayList<String>();
         map= new HashMap<>();
         while(rs.next())
         {
              String groupName = rs.getString(2);
    // add group names to the array list
              groupNames.add(groupName);
              map.put(groupName,rs.getString(1));
             
         }
         DefaultComboBoxModel model = new DefaultComboBoxModel(groupNames.toArray());
         c1.setModel(model);
         rs.close();
         
        }
        catch(Exception h)
        {
            
        }
          try
        {
            ConnectionDetails poo = new ConnectionDetails();
            Statement stmt = poo.con.createStatement();
         ResultSet rs = stmt.executeQuery("SELECT  `username`, `name`  FROM `employee_details` WHERE employeeType='Project Manager'" );
         ArrayList<String> groupNames = new ArrayList<String>();
         map1= new HashMap<>();
         while(rs.next())
         {
              String groupName = rs.getString(2);
              System.out.println(groupName);
    // add group names to the array list
              groupNames.add(groupName);
              map1.put(groupName,rs.getString(1));
              System.out.println(rs.getString(1));
              
         }
         DefaultComboBoxModel model = new DefaultComboBoxModel(groupNames.toArray());
         c2.setModel(model);
         
         
        }
        catch(Exception h)
        {
            
        }
         
          
          try
        {
            ConnectionDetails poo = new ConnectionDetails();
            Statement stmt = poo.con.createStatement();
         ResultSet rs = stmt.executeQuery("SELECT  `username`, `name`  FROM `employee_details` WHERE employeeType='Team Leader'");
         ArrayList<String> groupNames = new ArrayList<String>();
         map2= new HashMap<>();
         while(rs.next())
         {
              String groupName = rs.getString(2);
    // add group names to the array list
              groupNames.add(groupName);
              map2.put(groupName,rs.getString(1));
             
         }
         DefaultComboBoxModel model = new DefaultComboBoxModel(groupNames.toArray());
         c3.setModel(model);
         rs.close();
         
        }
        catch(Exception h)
        {
            
        }
           try
        {
            ConnectionDetails poo = new ConnectionDetails();
            Statement stmt = poo.con.createStatement();
         ResultSet rs = stmt.executeQuery("SELECT `username`, `name` FROM `employee_details` WHERE employeeType!='Project Manager' && employeeType!='Admin' && employeeType!='HR' ");
         ArrayList<String> groupNames = new ArrayList<String>();
         map3= new HashMap<>();
         while(rs.next())
         {
              String groupName = rs.getString(2);
    // add group names to the array list
              groupNames.add(groupName);
              map3.put(groupName,rs.getString(1));
             
         }
         DefaultComboBoxModel model = new DefaultComboBoxModel(groupNames.toArray());
         c4.setModel(model);
         rs.close();
         
        }
        catch(Exception h)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox();
        c2 = new javax.swing.JComboBox();
        c3 = new javax.swing.JComboBox();
        c4 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(900, 550));

        jLabel1.setText("Project Name");

        jLabel2.setText("Team Leader");

        jLabel3.setText("Project Manager");

        jLabel4.setText("Team Member");

        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        jButton1.setText("Allocation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ConnectionDetails c=new ConnectionDetails();
             PreparedStatement pd=c.con.prepareStatement("INSERT INTO `project_allocation`( `project_id`, `project_manager`, `team_leader`, `team_members`) VALUES (?,?,?,?);");
           
            pd.setString(1, map.get(c1.getSelectedItem().toString()));
          pd.setString(2, map1.get(c2.getSelectedItem().toString()));
          pd.setString(3, map2.get(c3.getSelectedItem().toString()));
          pd.setString(4, map3.get(c4.getSelectedItem().toString()));
         
            pd.executeUpdate();
            Component rootPane = null;
            JOptionPane.showConfirmDialog(rootPane, "Login Created");
            
        } catch (SQLException ex) {
            Logger.getLogger(CreateProject.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    HashMap<String,String> map;
    String projectname;
    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_c1ActionPerformed

     HashMap<String,String> map1;
     HashMap<String,String> map2;
     HashMap<String,String> map3;
   
    String projectManagername;
    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox c2;
    private javax.swing.JComboBox c3;
    private javax.swing.JComboBox c4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private void JOptionPane() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
