/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package artechemployeemanagementsystem;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Mofaqkhayrul Islam
 */
public class TableOfProjectDetails extends javax.swing.JPanel {

    /**
     * Creates new form TableOfProjectDetails
     */
    JTable table;
    public TableOfProjectDetails() throws SQLException {
        initComponents();
        setLayout(new FlowLayout());
        
        
        ConnectionDetails poo = new ConnectionDetails();
         Statement stmt = poo.con.createStatement();
         ResultSet rs = stmt.executeQuery("SELECT `project_id`, `client_id`, `name`, `description`, `companyNane`, `startDate`, `endDate` FROM `project_details`;");
         int row=0;
         while(rs.next())
         {
             row++;
         }
         //System.out.println(row);
         rs = stmt.executeQuery("SELECT `project_id`, `client_id`, `name`, `description`, `companyNane`, `startDate`, `endDate` FROM `project_details`;");
         Object[][] data=new Object[row][7];
         //Object[] colomn=new Object[7];
         Object[] colomn = {"Project ID", "Client ID", "Project Name", "Description", "Company Name", "Start Date", "End Date"};
        int i1=0;
//        colomn[0]="Name";
//        colomn[1]="Adress";
//        colomn[2]="Contact No";
//        colomn[3]="Email ID";
//        colomn[4]="Hired Date";
//        colomn[5]="Employee Type";
//        colomn[6]="Designation";
        
        
        while(rs.next()){
            for(int j1=0;j1<7;j1++)
            {
                    data[i1][j1]=rs.getString(j1+1);
            }
            i1++;
        }
        
        table = new JTable(data, colomn);
        table.setPreferredScrollableViewportSize(new Dimension(900, 550));
        table.setFillsViewportHeight(true);
        JScrollPane scrollPane = new JScrollPane(table);
        add(scrollPane);
         
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(900, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
